server:
  port: 8081

spring:
  ai:
    mcp:
      client:
        enabled: true
        name: demo-mcp-client
        version: 1.0.0
        type: SYNC
        initialized: true
        request-timeout: 30s
        streamable-http:
          connections:
            server-mcp:
              url: http://127.0.0.1:8080
             # endpoint: /yyy
    openai:
     api-key: ${OPENAI_API_KEY}
     chat:
      options:
        model: gpt-4o-mini
        temperature: 0.2

logging:
  level:
    org.springframework.ai.mcp: INFO
    io.modelcontextprotocol: INFO
